import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const spaceMono = Space_Mono({
  subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-space-mono"
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jasmine Sanders",
  description: "Generated by Jasmine Sanders",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${spaceMono.className} antialiase`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
